--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 15.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chapters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chapters (
    chapter_id bigint NOT NULL,
    chapter_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    display_order integer,
    estimated_questions integer,
    updated_at timestamp(6) without time zone NOT NULL,
    weightage integer,
    unit_id bigint NOT NULL,
    created_by bigint NOT NULL
);


ALTER TABLE public.chapters OWNER TO postgres;

--
-- Name: chapters_chapter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chapters ALTER COLUMN chapter_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chapters_chapter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    question_id bigint NOT NULL,
    correct_option character(1) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    difficulty character varying(255) NOT NULL,
    explanation text,
    option_a text NOT NULL,
    option_b text NOT NULL,
    option_c text NOT NULL,
    option_d text NOT NULL,
    question_text text NOT NULL,
    priority integer,
    source character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    year_asked integer,
    topic_id bigint NOT NULL,
    created_by bigint NOT NULL,
    CONSTRAINT questions_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])))
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- Name: questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questions ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subjects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subjects (
    subject_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    subject_name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.subjects OWNER TO postgres;

--
-- Name: subjects_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subjects ALTER COLUMN subject_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topic (
    topic_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    desciption character varying(255),
    displayorder integer,
    weightage integer,
    topic_name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    chapter_id bigint NOT NULL,
    created_by bigint NOT NULL
);


ALTER TABLE public.topic OWNER TO postgres;

--
-- Name: topic_topic_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.topic ALTER COLUMN topic_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topic_topic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: units; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.units (
    unit_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    unit_name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    subject_id bigint NOT NULL,
    created_by bigint NOT NULL
);


ALTER TABLE public.units OWNER TO postgres;

--
-- Name: units_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.units ALTER COLUMN unit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.units_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(30) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'STUDENT'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chapters chapters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chapters
    ADD CONSTRAINT chapters_pkey PRIMARY KEY (chapter_id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (question_id);


--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (subject_id);


--
-- Name: topic topic_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT topic_pkey PRIMARY KEY (topic_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: subjects ukgaix2pna1ulbxhdl4kbq9yglt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT ukgaix2pna1ulbxhdl4kbq9yglt UNIQUE (subject_name);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: units units_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (unit_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: chapters fk6bkdne3npj8d22vanuls1l3jx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chapters
    ADD CONSTRAINT fk6bkdne3npj8d22vanuls1l3jx FOREIGN KEY (created_by) REFERENCES public.users(user_id);


--
-- Name: chapters fk6jsc896qc7jj1jlooxe6px538; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chapters
    ADD CONSTRAINT fk6jsc896qc7jj1jlooxe6px538 FOREIGN KEY (unit_id) REFERENCES public.units(unit_id);


--
-- Name: units fk72qfm93ctr7iytcno768vaaro; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT fk72qfm93ctr7iytcno768vaaro FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id);


--
-- Name: topic fk9xnehdaasn6hd20d4l2c661h8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT fk9xnehdaasn6hd20d4l2c661h8 FOREIGN KEY (created_by) REFERENCES public.users(user_id);


--
-- Name: topic fkk8ia5h4a9w65a9krsvkn85x9f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.topic
    ADD CONSTRAINT fkk8ia5h4a9w65a9krsvkn85x9f FOREIGN KEY (chapter_id) REFERENCES public.chapters(chapter_id);


--
-- Name: questions fkmiy2i24hb8838iqkm2kunw286; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkmiy2i24hb8838iqkm2kunw286 FOREIGN KEY (created_by) REFERENCES public.users(user_id);


--
-- Name: questions fkr7jcounfykqgs9lm1wqy4vb4a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkr7jcounfykqgs9lm1wqy4vb4a FOREIGN KEY (topic_id) REFERENCES public.topic(topic_id);


--
-- Name: units fkreimfcdqop6n8d2qjj3s64eyk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.units
    ADD CONSTRAINT fkreimfcdqop6n8d2qjj3s64eyk FOREIGN KEY (created_by) REFERENCES public.users(user_id);


--
-- Name: tests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tests (
    test_id bigint NOT NULL,
    completed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    score integer,
    topic_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.tests ALTER COLUMN test_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tests_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: test_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.test_questions (
    test_id bigint NOT NULL,
    question_id bigint NOT NULL
);

--
-- Name: topic_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.topic_progress (
    progress_id bigint NOT NULL,
    topic_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.topic_progress ALTER COLUMN progress_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topic_progress_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_question_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_question_status (
    progress_id bigint NOT NULL,
    is_correct boolean,
    question_id bigint NOT NULL
);

--
-- Constraints and Keys
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_pkey PRIMARY KEY (test_id);

ALTER TABLE ONLY public.topic_progress
    ADD CONSTRAINT topic_progress_pkey PRIMARY KEY (progress_id);

ALTER TABLE ONLY public.user_question_status
    ADD CONSTRAINT user_question_status_pkey PRIMARY KEY (progress_id, question_id);

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT fk_tests_topic FOREIGN KEY (topic_id) REFERENCES public.topic(topic_id);

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT fk_tests_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.test_questions
    ADD CONSTRAINT fk_test_questions_test FOREIGN KEY (test_id) REFERENCES public.tests(test_id);

ALTER TABLE ONLY public.test_questions
    ADD CONSTRAINT fk_test_questions_question FOREIGN KEY (question_id) REFERENCES public.questions(question_id);

ALTER TABLE ONLY public.topic_progress
    ADD CONSTRAINT fk_topic_progress_topic FOREIGN KEY (topic_id) REFERENCES public.topic(topic_id);

ALTER TABLE ONLY public.topic_progress
    ADD CONSTRAINT fk_topic_progress_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.user_question_status
    ADD CONSTRAINT fk_user_question_status_progress FOREIGN KEY (progress_id) REFERENCES public.topic_progress(progress_id);

--
-- PostgreSQL database dump complete
--

