# JWT (Replace with your own secret key)

jwt.secret=YOUR_SECRET_KEY
jwt.expiration=86400000


# Database (Replace with your local credentials)

spring.datasource.url=jdbc:postgresql://localhost:5432/YOUR_DATABASE_NAME
spring.datasource.username=YOUR_DATABASE_USERNAME
spring.datasource.password=YOUR_DATABASE_PASSWORD